config/routes.rb
Rails3::Application.routes.draw do
  
  get "reports/index"
  post "reports/index"
  
  get "reports/salesman"
  post "reports/salesman"

  devise_for :users
  devise_for :sales_users

   get "dashboard/index"
  resources :sale_items do
    collection do
      get "destroy_me"
    end
  end
  resources :profiles do
    collection do
      get "my_profile"
    end
  end
  

    

   root :to => "sale_items#index"
   

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_filter :check_for_profile,:only=>[:create]
  def my_profile
    @profile=current_user.profile

    unless(@profile)
      @profile=Profile.new(params[:id])
    end
  end

  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  def new
    @profile = Profile.new(params[:id])
  end

  def create
    data=Hash.new
    data=params[:profile]
    data[:user_id]=current_user.id
    @profile = Profile.new(data)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to(my_profile_profiles_path,
          :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created,
          :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors,
          :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    data=Hash.new
    data=params[:profile]
    data[:user_id]=current_user.id
    respond_to do |format|
      if @profile.update_attributes(data)
        format.html { redirect_to my_profile_profiles_path, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def check_for_profile
    if(current_user.profile)
      redirect_to(root_path, :notice => 'Profile already exists.')
    end
  end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_edit.html.erb
<div id="content">
	<div class="block" id="block-tables">
		<div class="secondary-navigation">
			<ul class="wat-cf">
				<li class="first">
					<%=link_to "Dashboard",root_path%>
				</li>
				<li class="active">
					<%=link_to "My Profile","#"%>
				</li>
			</ul>
		</div>
		<div class="content">
			<h2 class="title">Edit Profile</h2>
			<div class="inner">
			<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
<% if @profile.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
	<ul>
		<% @profile.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<fieldset>
	<legend>
		Basic Information
	</legend>
	<div class="field">
		<label>Employee Code</label>
		<%= f.text_field :employee_id, :class=>"string"%>
	</div>
	<div class="field">
		<label>First Name</label>
		<%= f.text_field :first_name, :class=>"string"%>
	</div>
	<div class="field">
		<label>Last Name</label>
		<%= f.text_field :last_name, :class=>"string"%>
	</div>
	<div class="field">
		<label>Birth Date</label>
		<%= f.date_select :birth_date,:start_year=> 1950, :class=>"date"%>
	</div>
	<div class="field">
		<label>Address Line 1</label>
		<%= f.text_field :address_1, :class=>"string"%>
	</div>
	<div class="field">
		<label>Address Line 2</label>
		<%= f.text_field :address_2, :class=>"string"%>
	</div>
	<div class="field">
		<label>Landmark</label>
		<%= f.text_field :landmark, :class=>"string"%>
	</div>
	<div class="field">
		<label>City</label>
		<%= f.text_field :city, :class=>"string"%>
	</div>
	<div class="field">
		<label>Pincode</label>
		<%= f.text_field :pincode, :class=>"string"%>
	</div>
	<div class="field">
		<label>State</label>
		<%= f.text_field :state, :class=>"string"%>
	</div>
	<div class="field">
		<label>Country</label>
		<%= f.text_field :country, :class=>"string"%>
	</div>
	<div class="field">
		<label>Phone Number</label>
		<%= f.text_field :phone_number_1, :class=>"string"%>
	</div>
	<div class="field">
		<label>Alternate Number</label>
		<%= f.text_field :phone_number_2, :class=>"string"%>
	</div>
	<%if @profile.new_record?%>
		<%= f.submit "Create Profile"%>
	<%else%>
		<%= f.submit "Edit Profile"%>
	<%end%>
	<%=link_to "Cancel",my_profile_profiles_path%>
</fieldset>
<% end %> 

app/views/profiles/_new.html.erb
<div id="content">	<div class="block" id="block-tables">		<div class="secondary-navigation">			<ul class="wat-cf">				<li class="first">					<%= link_to "Dashboard",root_path%>				</li>				<li class="active">					<%= link_to "My Profile","#"%>				</li>			</ul>		</div>		<div class="content">			<h2 class="title">New Profile</h2>			<div class="inner">				<%= render 'form' %>			</div>		</div>	</div></div>

app/views/profiles/_show.html.erb
<div class="fieldset">
	<h4>Basic Information</h4>
	
<div class="field">
	<div class="label">Employee Code</div>
	<div class="value"><%=@profile.employee_id%></div>
</div>	
<div class="field">
	<div class="label">Name</div>
	<div class="value"><%=@profile.first_name%> <%=@profile.last_name%></div>
</div>

<div class="field">
	<div class="label">Birth Date</div>
	<div class="value"><%=@profile.birth_date%></div>
</div>

	
<div class="field">
	<div class="label">Address</div>
	<div class="value"><%=@profile.address_1%>,<%=@profile.address_2%>,<%=@profile.landmark%></div>
</div>	

<div class="field">
	<div class="label">City</div>
	<div class="value"><%=@profile.city%>-<%=@profile.pincode%></div>
</div>

<div class="field">
	<div class="label">State</div>
	<div class="value"><%=@profile.state%></div>
</div>
<div class="field">
	<div class="label">Country</div>
	<div class="value"><%=@profile.country%></div>
</div>
	<h4>Contact Details</h4>
<div class="field">
	<div class="label">Phone number</div>
	<div class="value"><%=@profile.phone_number_1%></div>
</div>
<div class="field">
	<div class="label">Alternate contact no.</div>
	<div class="value"><%=@profile.phone_number_2%></div>
</div>
<div class="field">
	<div class="label">Email</div>
	<div class="value"><%=@profile.user.email%></div>
</div>
</div>

app/views/profiles/edit.html.erb
<%= render :partial => 'edit' %>

app/views/profiles/my_profile.html.erb
<div id="content">
	<div class="block" id="block-tables">
		<div class="secondary-navigation">
			<ul class="wat-cf">
				<li class="first">
					<%= link_to "Dashboard",root_path%>
				</li>
				<li class="active">
					<%= link_to "My Profile","#"%>
				</li>
			</ul>
		</div>
		<div class="content">
			<h2 class="title">My Profile</h2>
			<div class="inner">
				<%if @profile.new_record?%>
					<div class="information">
						No profile data found.						
					</div>
					<div class="group navform wat-cf">
						<%=link_to "New Profile", new_profile_path,:class=>"button"%>
					</div>
				<%else%>
					<%=render :partial=>"show", :object=> @profile%>
					<div class="group navform wat-cf">
						<%=link_to "Edit Profile", edit_profile_path(@profile),:class=>"button"%>
					</div>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/profiles/new.html.erb
<%= render :partial => 'new',:object=> @profile %>