config/routes.rb
Rails3::Application.routes.draw do
  
  get "reports/index"
  post "reports/index"
  
  get "reports/salesman"
  post "reports/salesman"

  devise_for :users
  devise_for :sales_users

   get "dashboard/index"
  resources :sale_items do
    collection do
      get "destroy_me"
    end
  end
  resources :profiles do
    collection do
      get "my_profile"
    end
  end
  

    

   root :to => "sale_items#index"
   

end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base

  belongs_to :sales_user, :foreign_key => :user_id
  belongs_to :product
 
  
  validates_presence_of :user_id, :product_id, :quantity, :sale_date
  validates_numericality_of :quantity, :only_integer=>true
  validate :quantity_is_positive
  
  scope :find_sales_of_user, lambda{|user_id| where("user_id=?",user_id)}

  validate :check_date_if_future
  before_save :calculate_total

  # def self.calculate_total_cost(sales_item)
  # sales_item.total_cost=sales_item.quantity * sales_item.product.price.to_f
  # puts sales_item.total_cost
  # return sales_item
  # end
  #
  # def self.calculate_total_cost(sales_item)
  # sales_item.total_cost=sales_item.quantity * sales_item.product.price.to_f
  # puts sales_item.total_cost
  # return sales_item
  # end

  RailsAdmin.config do |config|
    config.model ::SaleItem do
      edit do
        field :user_id do
          label "Sales Man"
        end
        field :sale_date
        field :product_id
        field :quantity
      end
      list do
        field :user_id do
          label "Sales Man"
        end
        field :sale_date
        field :product_id
        field :quantity
        field :total_cost do
          label "Total Cost (in Rupees)"
        end
      end
    end
  end

  def calculate_total
    p "In before save"
    if (self.quantity)
      p "In valid"
    self.total_cost= self.quantity * self.product.price.to_f unless self.product.price.nil?
    else
      p "In invalid"
      errors.add(:quantity, "can't be zero or negative.")
    end
  end

  def check_date_if_future
    unless self.sale_date <= Date.today
      p "Invalid Date"
      errors.add(:sale_date, "can't be in the future.")
    end
  end
  
  def before_save
    
    if self.user_id == nil
      self.user_id = User.first.id
    end  
  end
  
  def quantity_is_positive
    p "&&&&&&&&********************&&&&&&&&&&&&"
    if self.quantity
    unless self.quantity > 0
      errors.add(:quantity, "cant'be zero or negative.")  
    end
    end
  end

end

app/controllers/sale_items_controller.rb
class SaleItemsController < ApplicationController
 
  before_filter :login_required
 
  before_filter :check_for_sales_date, :only=>[:edit, :update]
  before_filter :check_for_user, :only=>[:edit, :update]
  
  def show
    p "In show"
    @sales_item=SaleItem.find(params[:id])
  end
    
  def index
    #@sales_item=SaleItem.find_sales_of_user(current_sales_user.id) 
    p "###########################"
    p current_sales_user.id 
    @sales_items=SaleItem.where("user_id=?",current_sales_user.id)
    p @sales_items
    p Product.all
  end
  
  def destroy
    p current_sales_user
    p "In destroy"
    @sales_item=SaleItem.find(params[:id])
    p @sales_item
    p "**********************************"
    p current_sales_user
    @sales_item.destroy
    p current_sales_user
    flash[:notice]="Sales item destroyed successfully"
    p "Destoyed"
    redirect_to sale_items_path
  end
  
  def destroy_me
    p current_sales_user
    p "In destroy me"
    @sales_item=SaleItem.find(params[:id])
    @sales_item.destroy
    flash[:notice]="Sales item destroyed successfully"
    p "Destoyed"
    redirect_to sale_items_path
  end
  
  def new
    @product=Product.all
    @sales_item=SaleItem.new
  end

  def create
    @product=Product.all
    @sales_item=SaleItem.new(params[:sale_item])
    p params[:sale_item]
    @sales_item.user_id=current_sales_user.id
    #@sales_item=SaleItem.calculate_total_cost(@sales_item)
    respond_to do |format|
      
      if @sales_item.save
        format.html {redirect_to @sales_item, :notice=> "Sales Item created successfully."}
      else
        format.html{render :action=> :new}
      end
      
    end
  end

  def edit
    @product=Product.all
    @sales_item=SaleItem.find(params[:id])
  end

  def update
    p "In update"
    @product=Product.all
    @sales_item=SaleItem.find(params[:id])
    hash=params[:sale_item]
    #@sales_item=SaleItem.calculate_total_cost(@sales_item)
    #hash[:total_cost]=@sales_item.total_cost
    respond_to do |format|
      if @sales_item.update_attributes(hash)
        format.html { redirect_to @sales_item, :notice => 'Sales Item updated successfully.' }
      else
        format.html { render :action=> "edit" }
      end
    end
  end

  private

  def check_for_sales_date
    @sales_item=SaleItem.find(params[:id])
    unless((@sales_item.created_at+24.hours)>(DateTime.now))
      flash[:notice]="Sales item can't be updated after 24 hours of submission."
      Rails.logger.warn("Sales item cant be updated after 24 hours of submission") 
      redirect_to root_path
      return false
    end
    puts "Sales Item is updateable"
 end
 
 def check_for_user
   @sales_item=SaleItem.find(params[:id])
     unless @sales_item.user_id==current_sales_user.id
       flash[:notice]="You donot have access to that resource"
       puts "You dont have access to this resource"
       redirect_to root_path
       return false
     end   
     puts "Sales item belongs to the current user"
 end
end

app/views/sale_items/_form.html.erb
<%= form_for(@sales_item) do |f| %><% if @sales_item.errors.any? %><div id="error_explanation">	<div class="flash">		<div class="message error">			<h2><%= pluralize(@sales_item.errors.count, "error") %> prohibited this profile from being saved:</h2>			<ul>						<% @sales_item.errors.full_messages.each do |msg| %>					<li>						<%= msg %>			</div>			</div>		</li>		<% end %>	</ul></div><% end %><fieldset>	<legend>		Daily Sales for <%= current_sales_user.name%>	</legend>	<div class="field">		<label>Sales Date</label>		<%= f.date_select :sale_date,:default=>{:year=>Time.now.year, :month=>Time.now.month, :day=>Time.now.day},:end_year=> Time.now.year, :class=>"date"%>	</div>	<!--	<div class="field">	<label>Sales Date</label>	<%f.text_field :sale_date, :class=>"string", :id=>"salesDate"%>	</div>-->	<div class="field">		<label>Product</label>		<%= f.select :product_id, @product.collect{|p| [p.name,p.id]}, {:class=>"select"}%>	</div>	<div class="field">		<label>Quantity</label>		<%= f.text_field :quantity, :class=>"string"%>	</div>	<div class="group navform wat-cf">		<%= f.submit "Submit Sales"%>		<%= link_to "Cancel", sale_items_path%>	</div></fieldset><% end %> 

app/views/sale_items/_show.html.erb
<div class="fieldset">
	
	
<div class="field">
	<div class="label">Product Name</div>
	<div class="value"><%=@sales_item.product.name%></div>
</div>	
<div class="field">
	<div class="label">Quantity</div>
	<div class="value"><%=@sales_item.quantity%></div>
</div>
<div class="field">
	<div class="label">Total Cost</div>
	<div class="value">Rs. <%=sprintf"%.2f"%@sales_item.total_cost unless @sales_item.total_cost.nil?%></div>
</div>
<div class="field">
	<div class="label">Date</div>
	<div class="value"><%=@sales_item.sale_date%></div>
</div>
</div>

app/views/sale_items/edit.html.erb
<div id="content">
	<div id="block-tables" class="block">
		<div class="secondary-navigation">
			<ul class="wat-cf">
				<li class="first">
					<%= link_to "Dashboard",root_path%>
				</li>
				<li class="active">
					<%= link_to "Edit","#"%>
				</li>
			</ul>
		</div>
		<div class="content">
			<h2 class="title">Edit Daily Sales For <%= current_sales_user.name%>
			<div class="clear20"></div>
			<div class="inner">
				<%= render :partial => 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/sale_items/index.html.erb
<div id="content">
	<div id="block-tables" class="block">
		<div class="secondary-navigation">
			<ul class="wat-cf">
				<li class="first">
					<%= link_to "Dashboard",root_path%>
				</li>
				<li class="active">
					<%= link_to "List","#"%>
				</li>
			</ul>
		</div>
		<div class="content">
			<div class="control">
				<%= link_to "Add new",new_sale_item_path,:class=>"button"%>
			</div>
			<h2 class="title"><b>Sale Details for <%= current_sales_user.name%></b></h2>
			<div class="clear10"></div>
			<div class="inner">
				<table class="table grid">
					<tr>
						<th>Product Name</th>
						<th>Quantity</th>
						<th>Total Price</th>
						<th>Sale Date</th>
						<th class="last"></th>
					</tr>
					<%@sales_items.each do |sale|%>
					<tr>
						<td><%= sale.product.name%></td>
						<td><%= sale.quantity%></td>
						<td>Rs. <%=sprintf "%.2f"% sale.total_cost unless sale.total_cost.nil? %></td>
						<td><%= sale.sale_date%></td>
						<td class="last"><%= link_to "Show",sale_item_path(sale)%> | <%= link_to "Edit",edit_sale_item_path(sale)%> | <%= link_to "Delete",destroy_me_sale_items_path(:id=>sale.id), :confirm=>"Are you sure"%></td>
					</tr>
					<%end%>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/sale_items/new.html.erb
<div id="content">
	<div id="block-tables" class="block">
		<div class="secondary-navigation">
			<ul class="wat-cf">
				<li class="first">
					<%= link_to "Dashboard",root_path%>
				</li>
				<li class="active">
					<%= link_to "New","#"%>
				</li>
			</ul>
		</div>
		<div class="content">
			<h2 class="title">Add Daily Sales For <%= current_sales_user.name%>
			<div class="clear20"></div>
			<div class="inner">
				<%= render :partial => 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/sale_items/show.html.erb
<div id="content">
	<div class="block" id="block-tables">
		<div class="secondary-navigation">
			<ul class="wat-cf">
				<li class="first">
					<%= link_to "Dashboard",root_path%>
				</li>
				<li class="active">
					<%= link_to "Show","#"%>
				</li>
			</ul>
		</div>
		<div class="content">
			<h2 class="title">Sales Information</h2>
			<div class="inner">
				<%= render :partial=>"show", :object=> @profile%>
				<div class="group navform wat-cf">
					<%= link_to "Edit",edit_sale_item_path, :class=>"button" %>
					<%= link_to "Cancel", sale_items_path, :class=>"button"%>
				</div>
			</div>
		</div>
	</div>
</div>