config/routes.rb
Rails3::Application.routes.draw do
  
  get "reports/index"
  post "reports/index"
  
  get "reports/salesman"
  post "reports/salesman"

  devise_for :users
  devise_for :sales_users

   get "dashboard/index"
  resources :sale_items do
    collection do
      get "destroy_me"
    end
  end
  resources :profiles do
    collection do
      get "my_profile"
    end
  end
  

    

   root :to => "sale_items#index"
   

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<title>JAS Inc.</title>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type'>
		<meta content='NONE,NOARCHIVE' name='robots'>
		<link href="/stylesheets/rails_admin/theme/base.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/theme/jquery-ui.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/theme/formtastic.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/theme/jquery.tipsy.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/theme/uniform.default.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/theme/activo/style.css?1321947478" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/base.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/form.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/show.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>
		<script type="text/javascript">
			if( typeof jQuery == 'undefined') {
				document.write(unescape("%3Cscript src='/javascripts/rails_admin/jquery-1.5.1.min.js' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js" type="text/javascript"></script>
		<script type="text/javascript">
			if(!jQuery.ui) {
				document.write(unescape("%3Cscript src='/javascripts/rails_admin/jquery-ui-1.8.13.min.js' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="/javascripts/rails_admin/activo/jquery.localscroll.js?1311059048" type="text/javascript"></script>
		<script src="/javascripts/rails_admin/activo/jquery.scrollTo.js?1311059048" type="text/javascript"></script>
		<script src="/javascripts/rails_admin/activo/jquery.tipsy.js?1311059048" type="text/javascript"></script>
		<script src="/javascripts/rails_admin/activo/jquery.uniform.min.js?1311059048" type="text/javascript"></script>
		<script src="/javascripts/rails_admin/rails.js?1311059048" type="text/javascript"></script>
		<script src="/javascripts/rails_admin/application.js?1322822857" type="text/javascript"></script>
		<script src="/javascripts/rails_admin/ra.datetimepicker.js?1311059048" type="text/javascript"></script>
		<script src="/javascripts/rails_admin/activo/application.js?1311059048" type="text/javascript"></script>
		<link href="/stylesheets/rails_admin/list.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/dashboard.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<link href="/stylesheets/rails_admin/ra.timeline.css?1311059048" media="screen" rel="stylesheet" type="text/css" />
		<meta name="csrf-param" content="authenticity_token"/>
		<meta name="csrf-token" content="190Lq72KWBQYgfEOWoDEH44Pk/djyWuulK7tThjrW/I="/>
	</head>
</html>
<body class='rails_admin'>
	<div id='container'>
		<div id='header' style="background:#333333;height:80px;border-bottom:2px solid #999;">
			<h1 class='title'><a href ="/"><span class='red'>JAS Inc</span><span class="white"> ltd.</span></a></h1>
			<% if sales_user_signed_in? %>
			<div id="user-navigation" style="top:22px;">
				<ul class="wat-cf">
					<li class="headUser">
						Welcome, <%=current_sales_user.name%>
					</li>
					<% if check_edit_access %>
					<li>
						<a href="/admin"><img src="/stylesheets/rails_admin/theme/activo/images/session/config.png?1333774181" alt="Dashboard" original-title="Dashboard"></a>
					</li>
					<% end %>
					
					<li>
						<a href="/"><img title="Home" src="/stylesheets/rails_admin/theme/activo/images/session/home.png?1333774181" alt="Home"></a>
					</li>
					<% unless current_sales_user%>
					<li>
						<a href="/admin/user/1/edit"><img title="girishsambhare@gmail.com" src="/stylesheets/rails_admin/theme/activo/images/session/account.png?1333774181" alt="girishsambhare@gmail.com"></a>
					</li>
					<%end%>
					<li>
						<a href="/sales_users/sign_out"><img title="Log out" src="/stylesheets/rails_admin/theme/activo/images/session/logout.png?1333774181" alt="Log out"></a>
					</li>
					<li></li>
				</ul>
			</div>
			<%else%>
			<div id="user-navigation" style="top:22px;">
					<ul class="wat-cf">
						<li >
							<a href="/users/sign_in"><img src="/stylesheets/rails_admin/theme/activo/images/session/config.png?1333774181" alt="Admin Login" title="Admin Login"></a>
						</li>
						<li >
							<a href="/sales_users/sign_in"><img src="/stylesheets/rails_admin/theme/activo/images/session/account.png?1333774181" alt="Salesman Login" title="Salesman Login"></a>
						</li>
					</ul>
			</div>
			<% end %>
		</div>
		<div id='wrapper' class="wat-cf">
			<div id='main' style="width:97%;">
			<%if flash[:notice] %>
				<div class="flash">
					<div class="message notice">
						<p>
							<%= flash[:notice] %>
						</p>
					</div>
				</div>
			<%end%>
			
			<%if flash[:alert] %>
				<div class="flash">
					<div class="message notice">
						<p>
							<% flash.each do |name, msg| %>
							<%= content_tag :div, msg%>
							<% end %>
						</p>
					</div>
				</div>
			<%end %>
				
			<%= yield %>
			</div>
		</div>
	</div>
	</div>

<style>


.hasDatepicker {
    background-attachment: scroll;
    background-clip: border-box;
    background-color: transparent;
    background-image: url("../../images/rails_admin/calendar.png");
    background-origin: padding-box;
    background-position: right center;
    background-repeat: no-repeat;
    background-size: auto auto;
    padding-right: 20px;
    width: 150px;
    border-bottom-color: #E3E9EF;
    border-bottom-style: solid;
    border-bottom-width: 1px;
    border-left-color: #E3E9EF;
    border-left-style: solid;
    border-left-width: 1px;
    
    border-right-color-ltr-source: physical;
    border-right-color-rtl-source: physical;
    border-right-color-value: #DBDFE6;
    border-right-style-ltr-source: physical;
    border-right-style-rtl-source: physical;
    border-right-style-value: solid;
    border-right-width-ltr-source: physical;
    border-right-width-rtl-source: physical;
    border-right-width-value: 1px;
    border-top-color: #ABADB3;
    border-top-style: solid;
    border-top-width: 1px;
    font-family: Verdana,Geneva,sans-serif;
    font-size: 12px;
    padding-bottom: 5px;
    padding-left: 5px;
    padding-right: 5px;
    padding-top: 5px;
    
    
    }

</style>

<script>

$j(document).ready(function($){
  $(".date").each(function(){
  var data = $(this).val();
  
  $(this).datetimepicker({"showTime":false,"timepicker":{"amPmText":["",""],"minuteText":"Minute","value":"","showPeriod":false,"hourText":"Hour"},"datepicker":{"monthNamesShort":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"firstDay":1,"dayNames":["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],"dateFormat":"MM dd, yy","value":$(this).val(),"dayNamesMin":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"dayNamesShort":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"monthNames":["January","February","March","April","May","June","July","August","September","October","November","December"]}});
});
});

</script>

	
</body>